services:
  - type: web
    name: kitenga-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn den_hook_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
